# Generated by Django 4.2.2 on 2023-06-15 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='Choice_text',
            new_name='choice_text',
        ),
    ]
